package DAL.Models;
// Generated Jun 3, 2019 11:46:52 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name="Bill"
    ,schema="dbo"
    ,catalog="Virgo_Database"
)
public class Bill  implements java.io.Serializable {


     private int idbill;
     private PaymentType paymentType;
     private int total;
     private Timestamp time;
     private Set<Appointment> appointments = new HashSet<Appointment>(0);
     private Set<Item> items = new HashSet<Item>(0);

    public Bill() {
    }
  public Bill(int total, PaymentType paymentType) {
        this.total = total;
        this.paymentType = paymentType;
    }
	
    public Bill(int idbill, int total, Timestamp time) {
        this.idbill = idbill;
        this.total = total;
        this.time = time;
    }
    public Bill(int idbill, PaymentType paymentType, int total, Timestamp time, Set<Appointment> appointments, Set<Item> items) {
       this.idbill = idbill;
       this.paymentType = paymentType;
       this.total = total;
       this.time = time;
       this.appointments = appointments;
       this.items = items;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY) 

    
    @Column(name="IDBill", unique=true, nullable=false)
    public int getIdbill() {
        return this.idbill;
    }
    
    public void setIdbill(int idbill) {
        this.idbill = idbill;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PaymentType")
    public PaymentType getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }

    
    @Column(name="Total", nullable=false, scale=4)
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }

    @Column(name="Time", nullable=false, length=23)
    public Timestamp getTime() {
        return this.time;
    }
    
    public void setTime(Timestamp time) {
        this.time = time;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bill")
    public Set<Appointment> getAppointments() {
        return this.appointments;
    }
    
    public void setAppointments(Set<Appointment> appointments) {
        this.appointments = appointments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bill")
    public Set<Item> getItems() {
        return this.items;
    }
    
    public void setItems(Set<Item> items) {
        this.items = items;
    }




}


