package DAL.Models;
// Generated Jun 3, 2019 11:46:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BloodType generated by hbm2java
 */
@Entity
@Table(name="Blood_Type"
    ,schema="dbo"
    ,catalog="Virgo_Database"
)
public class BloodType  implements java.io.Serializable {


     private int idbloodType;
     private String type;
     private Set<Patient> patients = new HashSet<Patient>(0);

    public BloodType() {
    }

	
    public BloodType(int idbloodType, String type) {
        this.idbloodType = idbloodType;
        this.type = type;
    }
    public BloodType(int idbloodType, String type, Set<Patient> patients) {
       this.idbloodType = idbloodType;
       this.type = type;
       this.patients = patients;
    }
   
     @Id 

    
    @Column(name="IDBloodType", unique=true, nullable=false)
    public int getIdbloodType() {
        return this.idbloodType;
    }
    
    public void setIdbloodType(int idbloodType) {
        this.idbloodType = idbloodType;
    }

    
    @Column(name="Type")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bloodType")
    public Set<Patient> getPatients() {
        return this.patients;
    }
    
    public void setPatients(Set<Patient> patients) {
        this.patients = patients;
    }




}


