package DAL.Models;
// Generated Jun 3, 2019 11:46:52 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContactNextOfKin generated by hbm2java
 */
@Entity
@Table(name="Contact_NextOfKin"
    ,schema="dbo"
    ,catalog="Virgo_Database"
)
public class ContactNextOfKin  implements java.io.Serializable {


     private int idcontact;
     private NextOfKin nextOfKin;
     private String number;

    public ContactNextOfKin() {
    }

	
    public ContactNextOfKin(int idcontact, String number) {
        this.idcontact = idcontact;
        this.number = number;
    }
    
      public ContactNextOfKin(NextOfKin nextOfKin, String number) {
        this.nextOfKin = nextOfKin;
        this.number = number;
    }
    
    public ContactNextOfKin(int idcontact, NextOfKin nextOfKin, String number) {
       this.idcontact = idcontact;
       this.nextOfKin = nextOfKin;
       this.number = number;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDContact", unique=true, nullable=false)
    public int getIdcontact() {
        return this.idcontact;
    }
    
    public void setIdcontact(int idcontact) {
        this.idcontact = idcontact;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NextOfKinID")
    public NextOfKin getNextOfKin() {
        return this.nextOfKin;
    }
    
    public void setNextOfKin(NextOfKin nextOfKin) {
        this.nextOfKin = nextOfKin;
    }

    
    @Column(name="Number", nullable=false)
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }




}


