package DAL.Models;
// Generated Jun 3, 2019 3:10:05 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="Contact"
    ,schema="dbo"
    ,catalog="Virgo_Database"
)
public class Contact  implements java.io.Serializable {


     private int idcontact;
     private Patient patient;
     private String number;

    public Contact() {
    }

	
    public Contact(int idcontact, String number) {
        this.idcontact = idcontact;
        this.number = number;
    }
    public Contact(Patient patient, String number) {
       this.patient = patient;
       this.number = number;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDContact", unique=true, nullable=false)
    public int getIdcontact() {
        return this.idcontact;
    }
    
    public void setIdcontact(int idcontact) {
        this.idcontact = idcontact;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PatientID")
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="Number", nullable=false)
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }




}


