package DAL.Models;
// Generated Jun 3, 2019 11:46:52 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="Item"
    ,schema="dbo"
    ,catalog="Virgo_Database"
)
public class Item  implements java.io.Serializable {


     private int iditem;
     private Bill bill;
     private String itemName;
     private int price;

    public Item() {
    }

	
    public Item(int iditem, String itemName, int price) {
        this.iditem = iditem;
        this.itemName = itemName;
        this.price = price;
    }
    
       public Item(Bill bill, String itemName, int price) {
       this.bill = bill;
       this.itemName = itemName;
       this.price = price;
    }
    
    public Item(int iditem, Bill bill, String itemName, int price) {
       this.iditem = iditem;
       this.bill = bill;
       this.itemName = itemName;
       this.price = price;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY) 

    
    @Column(name="IDItem", unique=true, nullable=false)
    public int getIditem() {
        return this.iditem;
    }
    
    public void setIditem(int iditem) {
        this.iditem = iditem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BillID")
    public Bill getBill() {
        return this.bill;
    }
    
    public void setBill(Bill bill) {
        this.bill = bill;
    }

    
    @Column(name="ItemName", nullable=false)
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    
    @Column(name="Price", nullable=false, scale=4)
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }

    @Override
    public String toString() {
        return String.valueOf(getPrice()); //To change body of generated methods, choose Tools | Templates.
    }




}


