package DAL.Models;
// Generated Jun 3, 2019 11:46:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NextOfKin generated by hbm2java
 */
@Entity
@Table(name="NextOfKin"
    ,schema="dbo"
    ,catalog="Virgo_Database"
)
public class NextOfKin  implements java.io.Serializable {


     private int idnextOfKin;
     private Patient patient;
     private String name;
     private String middleName;
     private String surname;
     private String relationshipToOutpatient;
     private String addressStreet;
     private Integer addressDoorNo;
     private String addressArea;
     private String addressCity;
     private String addressState;
     private String addressPincode;
     private Set<ContactNextOfKin> contactNextOfKins = new HashSet<ContactNextOfKin>(0);

    public NextOfKin() {
    }

	
    public NextOfKin(int idnextOfKin, String name, String surname) {
        this.idnextOfKin = idnextOfKin;
        this.name = name;
        this.surname = surname;
    }
    
         public NextOfKin(Patient patient, String name, String middleName, String surname, String relationshipToOutpatient) {
       this.patient = patient;
       this.name = name;
       this.middleName = middleName;
       this.surname = surname;
       this.relationshipToOutpatient = relationshipToOutpatient;
    }
    
    public NextOfKin(Patient patient, String name, String middleName, String surname, String relationshipToOutpatient, String addressStreet, Integer addressDoorNo, String addressArea, String addressCity, String addressState, String addressPincode) {
       this.patient = patient;
       this.name = name;
       this.middleName = middleName;
       this.surname = surname;
       this.relationshipToOutpatient = relationshipToOutpatient;
       this.addressStreet = addressStreet;
       this.addressDoorNo = addressDoorNo;
       this.addressArea = addressArea;
       this.addressCity = addressCity;
       this.addressState = addressState;
       this.addressPincode = addressPincode;
    }
   
  @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDNextOfKin", unique=true, nullable=false)
    public int getIdnextOfKin() {
        return this.idnextOfKin;
    }
    
    public void setIdnextOfKin(int idnextOfKin) {
        this.idnextOfKin = idnextOfKin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PatientID")
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="MiddleName")
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="Surname", nullable=false)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="RelationshipToOutpatient")
    public String getRelationshipToOutpatient() {
        return this.relationshipToOutpatient;
    }
    
    public void setRelationshipToOutpatient(String relationshipToOutpatient) {
        this.relationshipToOutpatient = relationshipToOutpatient;
    }

    
    @Column(name="AddressStreet")
    public String getAddressStreet() {
        return this.addressStreet;
    }
    
    public void setAddressStreet(String addressStreet) {
        this.addressStreet = addressStreet;
    }

    
    @Column(name="AddressDoorNo")
    public Integer getAddressDoorNo() {
        return this.addressDoorNo;
    }
    
    public void setAddressDoorNo(Integer addressDoorNo) {
        this.addressDoorNo = addressDoorNo;
    }

    
    @Column(name="AddressArea")
    public String getAddressArea() {
        return this.addressArea;
    }
    
    public void setAddressArea(String addressArea) {
        this.addressArea = addressArea;
    }

    
    @Column(name="AddressCity")
    public String getAddressCity() {
        return this.addressCity;
    }
    
    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }

    
    @Column(name="AddressState")
    public String getAddressState() {
        return this.addressState;
    }
    
    public void setAddressState(String addressState) {
        this.addressState = addressState;
    }

    
    @Column(name="AddressPincode")
    public String getAddressPincode() {
        return this.addressPincode;
    }
    
    public void setAddressPincode(String addressPincode) {
        this.addressPincode = addressPincode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nextOfKin")
    public Set<ContactNextOfKin> getContactNextOfKins() {
        return this.contactNextOfKins;
    }
    
    public void setContactNextOfKins(Set<ContactNextOfKin> contactNextOfKins) {
        this.contactNextOfKins = contactNextOfKins;
    }




}


