package DAL.Models;
// Generated Jun 3, 2019 3:10:05 AM by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name="Patient"
    ,schema="dbo"
    ,catalog="Virgo_Database"
)
public class Patient  implements java.io.Serializable {


     private int idpatient;
     private Integer bloodType;
     private int sexID;
     private String opid;
     private String name;
     private String middleName;
     private String surname;
     private Date dateOfBirth;
     private Timestamp dateAdded;
     private String briefStatementOfComplaint;
     private String presentAddressStreet;
     private Integer presentAddressDoorNo;
     private String presentAddressArea;
     private String presentAddressCity;
     private String presentAddressState;
     private String presentAddressPincode;
     private String permanentAddressStreet;
     private Integer permanentAddressDoorNo;
     private String permanentAddressArea;
     private String permanentAddressCity;
     private String permanentAddressState;
     private String permanentAddressPincode;
     private String maritalStatus;
     private Integer numberOfDependents;
     private Integer height;
     private Integer weight;
     private String occupation;
     private Integer grossAnnualIncome;
     private Boolean vegetarian;
     private Boolean smoker;
     private Integer averageNumberOfCigarettesPerDay;
     private Boolean consumeAlcoholicBeverage;
     private Integer averageNumberOfDrinksPerDay;
     private String stimulants;
     private Integer consumptionOfCoffeeTeaPerDay;
     private Integer consumptionOfSoftDrinksPerDay;
     private Boolean eatHomeOutsidePredominantly;
     private Boolean haveRegularMeals;
     private String statementOfComplaint;
     private String historyOfPreviousTreatment;
     private String physicianHospitalTreated;
     private Boolean diabetic;
     private Boolean hypertensive;
     private String cardiacCondition;
     private String respiratoryCondition;
     private String digestiveCondition;
     private String orthopedicCondition;
     private String muscularCondition;
     private String neurologicalCondition;
     private String knownAlergies;
     private String knownAdverseReactionToSpecificDrugs;
     private String majorSurgeriesHistory;
     private Integer doctorId;
     private Set<Contact> contacts = new HashSet<Contact>(0);
     private Set<NextOfKin> nextOfKins = new HashSet<NextOfKin>(0);
     private Set<Appointment> appointments = new HashSet<Appointment>(0);

    public Patient() {
    }
public Patient(String name,String middleName, String surname, int sexID, Date dateOfBirth, String statementOfComplaint ) {
        this.name = name;
        this.middleName = middleName;
        this.surname = surname;
        this.sexID = sexID;
        this.dateOfBirth = dateOfBirth;
        this.statementOfComplaint = statementOfComplaint;
    }
    
public Patient(Integer doctorId){
    this.doctorId = doctorId;
}
	
    public Patient(int idpatient, String name, String surname, String briefStatementOfComplaint) {
        this.idpatient = idpatient;
        this.name = name;
        this.surname = surname;
        this.briefStatementOfComplaint = briefStatementOfComplaint;
    }
    public Patient(Integer bloodType, int sexID, String opid, String name, String middleName,
            String surname, Date dateOfBirth, String briefStatementOfComplaint,
            String presentAddressStreet, Integer presentAddressDoorNo, 
            String presentAddressArea, String presentAddressCity, String presentAddressState,
            String presentAddressPincode, String permanentAddressStreet, Integer permanentAddressDoorNo, 
            String permanentAddressArea, String permanentAddressCity, String permanentAddressState, 
            String permanentAddressPincode, String maritalStatus, Integer numberOfDependents, Integer height, 
            Integer weight, String occupation, Integer grossAnnualIncome, Boolean vegetarian, Boolean smoker, 
            Integer averageNumberOfCigarettesPerDay, Boolean consumeAlcoholicBeverage, Integer averageNumberOfDrinksPerDay,
            String stimulants, Integer consumptionOfCoffeeTeaPerDay, Integer consumptionOfSoftDrinksPerDay, Boolean haveRegularMeals,
            Boolean eatHomeOutsidePredominantly, String statementOfComplaint, String historyOfPreviousTreatment,
            String physicianHospitalTreated, Boolean diabetic, Boolean hypertensive, String cardiacCondition, 
            String respiratoryCondition, String digestiveCondition, String orthopedicCondition, String muscularCondition, 
            String neurologicalCondition, String knownAlergies, String knownAdverseReactionToSpecificDrugs, String majorSurgeriesHistory) {
       this.bloodType = bloodType;
       this.sexID = sexID;
       this.opid = opid;
       this.name = name;
       this.middleName = middleName;
       this.surname = surname;
       this.dateOfBirth = dateOfBirth;
       this.briefStatementOfComplaint = briefStatementOfComplaint;
       this.presentAddressStreet = presentAddressStreet;
       this.presentAddressDoorNo = presentAddressDoorNo;
       this.presentAddressArea = presentAddressArea;
       this.presentAddressCity = presentAddressCity;
       this.presentAddressState = presentAddressState;
       this.presentAddressPincode = presentAddressPincode;
       this.permanentAddressStreet = permanentAddressStreet;
       this.permanentAddressDoorNo = permanentAddressDoorNo;
       this.permanentAddressArea = permanentAddressArea;
       this.permanentAddressCity = permanentAddressCity;
       this.permanentAddressState = permanentAddressState;
       this.permanentAddressPincode = permanentAddressPincode;
       this.maritalStatus = maritalStatus;
       this.numberOfDependents = numberOfDependents;
       this.height = height;
       this.weight = weight;
       this.occupation = occupation;
       this.grossAnnualIncome = grossAnnualIncome;
       this.vegetarian = vegetarian;
       this.smoker = smoker;
       this.averageNumberOfCigarettesPerDay = averageNumberOfCigarettesPerDay;
       this.consumeAlcoholicBeverage = consumeAlcoholicBeverage;
       this.averageNumberOfDrinksPerDay = averageNumberOfDrinksPerDay;
       this.stimulants = stimulants;
       this.consumptionOfCoffeeTeaPerDay = consumptionOfCoffeeTeaPerDay;
       this.consumptionOfSoftDrinksPerDay = consumptionOfSoftDrinksPerDay;
       this.haveRegularMeals = haveRegularMeals;
       this.eatHomeOutsidePredominantly = eatHomeOutsidePredominantly;
       this.statementOfComplaint = statementOfComplaint;
       this.historyOfPreviousTreatment = historyOfPreviousTreatment;
       this.physicianHospitalTreated = physicianHospitalTreated;
       this.diabetic = diabetic;
       this.hypertensive = hypertensive;
       this.cardiacCondition = cardiacCondition;
       this.respiratoryCondition = respiratoryCondition;
       this.digestiveCondition = digestiveCondition;
       this.orthopedicCondition = orthopedicCondition;
       this.muscularCondition = muscularCondition;
       this.neurologicalCondition = neurologicalCondition;
       this.knownAlergies = knownAlergies;
       this.knownAdverseReactionToSpecificDrugs = knownAdverseReactionToSpecificDrugs;
       this.majorSurgeriesHistory = majorSurgeriesHistory;
       this.dateAdded = dateAdded;
    }
   
        @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDPatient", unique=true, nullable=false)
    public int getIdpatient() {
        return this.idpatient;
    }
    
    public void setIdpatient(int idpatient) {
        this.idpatient = idpatient;
    }

@Column(name="BloodType")
    public Integer getBloodType() {
        return this.bloodType;
    }
    
    public void setBloodType(Integer bloodType) {
        this.bloodType = bloodType;
    }
    
    @Column(name="OPID")
    public String getOpid() {
        return this.opid;
    }
    
    public void setOpid(String opid) {
        this.opid = opid;
    }

    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="MiddleName")
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="Surname", nullable=false)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    
    
    @Column(name="SexID", nullable=false)
    public int getSexId() {
        return this.sexID;
    }
    
    public void setSexId(Integer sexId) {
        this.sexID = sexId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DateOfBirth", length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    
    @Column(name="DateAdded", length=10)
    public Timestamp getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Timestamp dateAdded) {
        this.dateAdded = dateAdded;
    }

    
    @Column(name="BriefStatementOfComplaint")
    public String getBriefStatementOfComplaint() {
        return this.briefStatementOfComplaint;
    }
    
    public void setBriefStatementOfComplaint(String briefStatementOfComplaint) {
        this.briefStatementOfComplaint = briefStatementOfComplaint;
    }

    
    @Column(name="PresentAddressStreet")
    public String getPresentAddressStreet() {
        return this.presentAddressStreet;
    }
    
    public void setPresentAddressStreet(String presentAddressStreet) {
        this.presentAddressStreet = presentAddressStreet;
    }

    
    @Column(name="PresentAddressDoorNo")
    public Integer getPresentAddressDoorNo() {
        return this.presentAddressDoorNo;
    }
    
    public void setPresentAddressDoorNo(Integer presentAddressDoorNo) {
        this.presentAddressDoorNo = presentAddressDoorNo;
    }

    
    @Column(name="PresentAddressArea")
    public String getPresentAddressArea() {
        return this.presentAddressArea;
    }
    
    public void setPresentAddressArea(String presentAddressArea) {
        this.presentAddressArea = presentAddressArea;
    }

    
    @Column(name="PresentAddressCity")
    public String getPresentAddressCity() {
        return this.presentAddressCity;
    }
    
    public void setPresentAddressCity(String presentAddressCity) {
        this.presentAddressCity = presentAddressCity;
    }

    
    @Column(name="PresentAddressState")
    public String getPresentAddressState() {
        return this.presentAddressState;
    }
    
    public void setPresentAddressState(String presentAddressState) {
        this.presentAddressState = presentAddressState;
    }

    
    @Column(name="PresentAddressPincode")
    public String getPresentAddressPincode() {
        return this.presentAddressPincode;
    }
    
    public void setPresentAddressPincode(String presentAddressPincode) {
        this.presentAddressPincode = presentAddressPincode;
    }

    
    @Column(name="PermanentAddressStreet")
    public String getPermanentAddressStreet() {
        return this.permanentAddressStreet;
    }
    
    public void setPermanentAddressStreet(String permanentAddressStreet) {
        this.permanentAddressStreet = permanentAddressStreet;
    }

    
    @Column(name="PermanentAddressDoorNo")
    public Integer getPermanentAddressDoorNo() {
        return this.permanentAddressDoorNo;
    }
    
    public void setPermanentAddressDoorNo(Integer permanentAddressDoorNo) {
        this.permanentAddressDoorNo = permanentAddressDoorNo;
    }

    
    @Column(name="PermanentAddressArea")
    public String getPermanentAddressArea() {
        return this.permanentAddressArea;
    }
    
    public void setPermanentAddressArea(String permanentAddressArea) {
        this.permanentAddressArea = permanentAddressArea;
    }

    
    @Column(name="PermanentAddressCity")
    public String getPermanentAddressCity() {
        return this.permanentAddressCity;
    }
    
    public void setPermanentAddressCity(String permanentAddressCity) {
        this.permanentAddressCity = permanentAddressCity;
    }

    
    @Column(name="PermanentAddressState")
    public String getPermanentAddressState() {
        return this.permanentAddressState;
    }
    
    public void setPermanentAddressState(String permanentAddressState) {
        this.permanentAddressState = permanentAddressState;
    }

    
    @Column(name="PermanentAddressPincode")
    public String getPermanentAddressPincode() {
        return this.permanentAddressPincode;
    }
    
    public void setPermanentAddressPincode(String permanentAddressPincode) {
        this.permanentAddressPincode = permanentAddressPincode;
    }

    
    @Column(name="MaritalStatus")
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    
    @Column(name="NumberOfDependents")
    public Integer getNumberOfDependents() {
        return this.numberOfDependents;
    }
    
    public void setNumberOfDependents(Integer numberOfDependents) {
        this.numberOfDependents = numberOfDependents;
    }

    
    @Column(name="Height")
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }

    
    @Column(name="Weight")
    public Integer getWeight() {
        return this.weight;
    }
    
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    
    @Column(name="Occupation")
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    
    @Column(name="GrossAnnualIncome")
    public Integer getGrossAnnualIncome() {
        return this.grossAnnualIncome;
    }
    
    public void setGrossAnnualIncome(Integer grossAnnualIncome) {
        this.grossAnnualIncome = grossAnnualIncome;
    }

    
    @Column(name="Vegetarian")
    public Boolean getVegetarian() {
        return this.vegetarian;
    }
    
    public void setVegetarian(Boolean vegetarian) {
        this.vegetarian = vegetarian;
    }

    
    @Column(name="Smoker")
    public Boolean getSmoker() {
        return this.smoker;
    }
    
    public void setSmoker(Boolean smoker) {
        this.smoker = smoker;
    }

    
    @Column(name="AverageNumberOfCigarettesPerDay")
    public Integer getAverageNumberOfCigarettesPerDay() {
        return this.averageNumberOfCigarettesPerDay;
    }
    
    public void setAverageNumberOfCigarettesPerDay(Integer averageNumberOfCigarettesPerDay) {
        this.averageNumberOfCigarettesPerDay = averageNumberOfCigarettesPerDay;
    }

    
    @Column(name="ConsumeAlcoholicBeverage")
    public Boolean getConsumeAlcoholicBeverage() {
        return this.consumeAlcoholicBeverage;
    }
    
    public void setConsumeAlcoholicBeverage(Boolean consumeAlcoholicBeverage) {
        this.consumeAlcoholicBeverage = consumeAlcoholicBeverage;
    }

    
    @Column(name="AverageNumberOfDrinksPerDay")
    public Integer getAverageNumberOfDrinksPerDay() {
        return this.averageNumberOfDrinksPerDay;
    }
    
    public void setAverageNumberOfDrinksPerDay(Integer averageNumberOfDrinksPerDay) {
        this.averageNumberOfDrinksPerDay = averageNumberOfDrinksPerDay;
    }

    
    @Column(name="Stimulants")
    public String getStimulants() {
        return this.stimulants;
    }
    
    public void setStimulants(String stimulants) {
        this.stimulants = stimulants;
    }

    
    @Column(name="ConsumptionOfCoffee_TeaPerDay")
    public Integer getConsumptionOfCoffeeTeaPerDay() {
        return this.consumptionOfCoffeeTeaPerDay;
    }
    
    public void setConsumptionOfCoffeeTeaPerDay(Integer consumptionOfCoffeeTeaPerDay) {
        this.consumptionOfCoffeeTeaPerDay = consumptionOfCoffeeTeaPerDay;
    }

    
    @Column(name="ConsumptionOfSoftDrinksPerDay")
    public Integer getConsumptionOfSoftDrinksPerDay() {
        return this.consumptionOfSoftDrinksPerDay;
    }
    
    public void setConsumptionOfSoftDrinksPerDay(Integer consumptionOfSoftDrinksPerDay) {
        this.consumptionOfSoftDrinksPerDay = consumptionOfSoftDrinksPerDay;
    }

     @Column(name="HaveRegularMeals")
    public Boolean getHaveRegularMeals() {
        return this.haveRegularMeals;
    }
    
    public void setHaveRegularMeals(Boolean haveRegularMeals) {
        this.haveRegularMeals = haveRegularMeals;
    }
    
    @Column(name="EatHome_OutsidePredominantly")
    public Boolean getEatHomeOutsidePredominantly() {
        return this.eatHomeOutsidePredominantly;
    }
    
    public void setEatHomeOutsidePredominantly(Boolean eatHomeOutsidePredominantly) {
        this.eatHomeOutsidePredominantly = eatHomeOutsidePredominantly;
    }

    
    @Column(name="StatementOfComplaint")
    public String getStatementOfComplaint() {
        return this.statementOfComplaint;
    }
    
    public void setStatementOfComplaint(String statementOfComplaint) {
        this.statementOfComplaint = statementOfComplaint;
    }

    
    @Column(name="HistoryOfPreviousTreatment")
    public String getHistoryOfPreviousTreatment() {
        return this.historyOfPreviousTreatment;
    }
    
    public void setHistoryOfPreviousTreatment(String historyOfPreviousTreatment) {
        this.historyOfPreviousTreatment = historyOfPreviousTreatment;
    }

    
    @Column(name="Physician_HospitalTreated")
    public String getPhysicianHospitalTreated() {
        return this.physicianHospitalTreated;
    }
    
    public void setPhysicianHospitalTreated(String physicianHospitalTreated) {
        this.physicianHospitalTreated = physicianHospitalTreated;
    }

    
    @Column(name="Diabetic")
    public Boolean getDiabetic() {
        return this.diabetic;
    }
    
    public void setDiabetic(Boolean diabetic) {
        this.diabetic = diabetic;
    }

    
    @Column(name="Hypertensive")
    public Boolean getHypertensive() {
        return this.hypertensive;
    }
    
    public void setHypertensive(Boolean hypertensive) {
        this.hypertensive = hypertensive;
    }

    
    @Column(name="CardiacCondition")
    public String getCardiacCondition() {
        return this.cardiacCondition;
    }
    
    public void setCardiacCondition(String cardiacCondition) {
        this.cardiacCondition = cardiacCondition;
    }

    
    @Column(name="RespiratoryCondition")
    public String getRespiratoryCondition() {
        return this.respiratoryCondition;
    }
    
    public void setRespiratoryCondition(String respiratoryCondition) {
        this.respiratoryCondition = respiratoryCondition;
    }

    
    @Column(name="DigestiveCondition")
    public String getDigestiveCondition() {
        return this.digestiveCondition;
    }
    
    public void setDigestiveCondition(String digestiveCondition) {
        this.digestiveCondition = digestiveCondition;
    }

    
    @Column(name="OrthopedicCondition")
    public String getOrthopedicCondition() {
        return this.orthopedicCondition;
    }
    
    public void setOrthopedicCondition(String orthopedicCondition) {
        this.orthopedicCondition = orthopedicCondition;
    }

    
    @Column(name="MuscularCondition")
    public String getMuscularCondition() {
        return this.muscularCondition;
    }
    
    public void setMuscularCondition(String muscularCondition) {
        this.muscularCondition = muscularCondition;
    }

    
    @Column(name="NeurologicalCondition")
    public String getNeurologicalCondition() {
        return this.neurologicalCondition;
    }
    
    public void setNeurologicalCondition(String neurologicalCondition) {
        this.neurologicalCondition = neurologicalCondition;
    }

    
    @Column(name="KnownAlergies")
    public String getKnownAlergies() {
        return this.knownAlergies;
    }
    
    public void setKnownAlergies(String knownAlergies) {
        this.knownAlergies = knownAlergies;
    }

    
    @Column(name="KnownAdverseReactionToSpecificDrugs")
    public String getKnownAdverseReactionToSpecificDrugs() {
        return this.knownAdverseReactionToSpecificDrugs;
    }
    
    public void setKnownAdverseReactionToSpecificDrugs(String knownAdverseReactionToSpecificDrugs) {
        this.knownAdverseReactionToSpecificDrugs = knownAdverseReactionToSpecificDrugs;
    }

    
    @Column(name="MajorSurgeriesHistory")
    public String getMajorSurgeriesHistory() {
        return this.majorSurgeriesHistory;
    }
    
    public void setMajorSurgeriesHistory(String majorSurgeriesHistory) {
        this.majorSurgeriesHistory = majorSurgeriesHistory;
    }
    
      @Column(name="DoctorId")
    public Integer getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="patient")
    public Set<Contact> getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set<Contact> contacts) {
        this.contacts = contacts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="patient")
    public Set<NextOfKin> getNextOfKins() {
        return this.nextOfKins;
    }
    
    public void setNextOfKins(Set<NextOfKin> nextOfKins) {
        this.nextOfKins = nextOfKins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="patient")
    public Set<Appointment> getAppointments() {
        return this.appointments;
    }
    
    public void setAppointments(Set<Appointment> appointments) {
        this.appointments = appointments;
    }

public static String[] patientColumns(){
        String[] columns = {
        "OPID", "Name", "Middle Name", "Surname", "Date Of Birth", "Sex", "", "Present Address", "Permanent Address", "Next Of Kin"
        };
        return columns;
    }

    @Override
    public String toString() {
        return getName() + " " + getSurname();
    }



}


